In [1]:
import findspark
findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("clusterizacao").config("spark.driver.memory", "10g").getOrCreate()

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 55824)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "c:\Dev\projeto2_clusterizacao\venv\lib\site-packages\pyspark\accumulators.py", line 295, in handle
  File "c:\Dev\projeto2_clusterizacao\venv\lib\site-packages\pyspark\accumulators.py", line 267, in poll
  File "c:\Dev\projeto2_clusterizacao\venv\lib\site-packages\pyspark\accumulators.py", line 271, in accum_updates
  File "c:\Dev\projeto2_clusterizacao\venv\lib\site-packages\pyspark\serializers.py", line 594, in read_int
    length = stream.read(4)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto
----------------------------------------

Limpando e normalizando o texto

In [2]:
import nltk
from nltk.corpus import stopwords

from pyspark.ml.feature import StopWordsRemover, RegexTokenizer
from pyspark.sql.functions import col

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jonas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
stopwords_en = set(stopwords.words('english'))

In [5]:
print(f"Total de stopwords em inglês: {len(stopwords_en)}")

print(f"Lista das 10 primeiras stopwords: {list(stopwords_en)[:10]}")

Total de stopwords em inglês: 179
Lista das 10 primeiras stopwords: ['isn', 'have', 'i', 'which', 'our', 'hadn', 'that', 'are', "doesn't", 've']

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('resources\dblp-v10-clean.csv')

In [8]:
pd.set_option('display.max_colwidth', None)
df[['id', 'abstract']].head()

,id,abstract
0,4ab3735c-80f1-472d-b953-fa0557fed28b,"In this paper, a robust 3D triangular mesh watermarking algorithm based on 3D segmentation is proposed. In this algorithm three classes of watermarking are combined. First, we segment the original image to many different regions. Then we mark every type of region with the corresponding algorithm based on their curvature value. The experiments show that our watermarking is robust against numerous attacks including RST transformations, smoothing, additive random noise, cropping, simplification and remeshing."
1,4ab39729-af77-46f7-a662-16984fb9c1db,"We studied an autoassociative neural network with dynamic synapses which include a facilitating mechanism. We have developed a general mean-field framework to study the relevance of the different parameters defining the dynamics of the synapses and their influence on the collective properties of the network. Depending on these parameters, the network shows different types of behaviour including a retrieval phase, an oscillatory regime, and a non-retrieval phase. In the oscillatory phase, the network activity continously jumps between the stored patterns. Compared with other activity-dependent mechanisms such as synaptic depression, synaptic facilitation enhances the network ability to switch among the stored patterns and, therefore, its adaptation to external stimuli. A detailed analysis of our system reflects an efficient-more rapid and with lesser errors-network access to the stored information with stronger facilitation. We also present a set of Monte Carlo simulations confirming our analytical results."
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,"It is well-known that Sturmian sequences are the non ultimately periodic sequences that are balanced over a 2-letter alphabet. They are also characterized by their complexity: they have exactly $(n+1)$ distinct factors of length $n$. A natural generalization of Sturmian sequences is the set of infinite episturmian sequences. These sequences are not necessarily balanced over a $k$-letter alphabet, nor are they necessarily aperiodic. In this paper, we characterize balanced episturmian sequences, periodic or not, and prove Fraenkel's conjecture for the special case of episturmian sequences. It appears that balanced episturmian sequences are all ultimately periodic and they can be classified in 3 families."
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,"One of the fundamental challenges of recognizing actions is accounting for the variability that arises when arbitrary cameras capture humans performing actions. In this paper, we explicitly identify three important sources of variability: (1) viewpoint, (2) execution rate, and (3) anthropometry of actors, and propose a model of human actions that allows us to investigate all three. Our hypothesis is that the variability associated with the execution of an action can be closely approximated by a linear combination of action bases in joint spatio-temporal space. We demonstrate that such a model bounds the rank of a matrix of image measurements and that this bound can be used to achieve recognition of actions based only on imaged data. A test employing principal angles between subspaces that is robust to statistical fluctuations in measurement data is presented to find the membership of an instance of an action. The algorithm is applied to recognize several actions, and promising results have been obtained."
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,"This paper generalizes previous optimal upper bounds on the minimum Euclidean distance for phase shift keying (PSK) block codes, that are explicit in three parameters: alphabet size, block length a ..."

In [9]:
df[['id', 'abstract']].tail()

,id,abstract
827528,feb7d7ee-58d8-4a48-853e-c6751957997e,"Abstract The article presents a narrative review of scholarship on social support through social networking sites (SNSs) published from 2004 to 2015. By searching keywords related to social support and SNSs in major databases for social sciences, we identified and content analyzed directly relevant articles (N = 88). The article summarizes the prevalence of theory usage; the function of theory usage (e.g., testing a theory, developing a theory); major theories referenced; and methodologies, including research designs, measurement, and the roles of social support and SNS examined in this literature. It also reports four themes identified across the studies, indicating the trends in the current research. Based on the review, the article presents a discussion about study sites, conceptualization of social support, theoretical coherence, the role of social networks, and the dynamic relationships between SNS use and social support, which points out potential avenues for shaping a future research agenda."
827529,ff21f451-e914-4948-b1e4-0ef5971b365c,"In MANETs, exchange of data is carried out with the help neighbouring nodes, and the destination node is identified with the broadcasting schemes. Broadcasting schemes are considered to increase the efficiency, and MPR broadcasting scheme is considered because of its reduced overhead. The message is broadcasted only to the selected MPR nodes, thus reducing flooding in the network. Nodes that are selected to act as the MPR nodes can be any neighbouring nodes, and there are no significant conditions that prove the MPR node's integrity. In this paper, we have proposed a novel approach in selecting the MPR nodes by adding an additional security feature before MPR node selection. Our security feature does not add any additional communicational overhead or data exchanges. We were also able to reduce the localisation error by using Mahalanobis distance and maximum-likelihood. Localisation techniques were used during simulation to verify the time constraints and efficiency."
827530,ff4623da-cc5a-4048-99ae-e5e906eb0a1b,"This paper presents a micro-power photovoltaic (PV) harvesting system. A H-bridge configuration DC-DC converter is designed to harvest PV energy and deliver energy to applications of Internet of Thing (IOT). The main converter consists of a single inductor with two inputs and two outputs. It regulates a constant 1V output voltage for several applications such as sensors and signal transmitters. The surplus energy is stored in a rechargeable battery. The battery also serves as a secondary input source to provide energy to the output load in heavy-load condition. Due to the limited energy of the system, the power consumption of the power system is optimized by several techniques. A perturb-and-observe maximum power point tracker (MPPT) is implemented to maximize the power extracted from the PV harvester. Pulse-width modulation (PWM) and pulse-frequency modulation (PFM) are used to regulate the output voltage. The controller is designed mainly in digital and free of power-hungry circuits. The proposed converter occupies an area of 1.44mm 2 . The estimated peak power efficiency is 84% while driving 3–10µA load current."
827531,ff6217c8-a649-4db3-95ec-e1c55195ef4e,"In this work, a distillation system is designed to purify dimethyl ether (DME) from its reaction by-products in the conversion of flare gas into a useful energy product. The distillation equipment has a size constraint for easy transportation, making process intensification the best strategy to efficiently separate the mixture. The process intensification distillation techniques explored include the dividing wall column (DWC) and a novel semicontinuous dividing wall column (S-DWC). The DWC and the S-DWC both purify DME to fuel grade purity along with producing high purity waste streams. An economic comparison is made between the two systems. The DWC is a cheaper method of producing DME however the purity of methanol, a reaction intermediate, is not as high as the S-DWC. Overall, this research shows that it is possible to purify DME and its reaction by-products in a 40-foot distillation column at a cost that is competitive with Diesel."
827532,ff87696d-35fb-4872-aab5-5ff6285f10e6,"The uninorms with continuous underlying t-norm and t-conorm are characterized via the ordinal sum construction of Clifford. Using the previous results of the author, where each uninorm with continuous underlying operations was characterized by properties of its set of discontinuity points, it is shown that each such a uninorm can be decomposed into an ordinal sum of a countable number of semigroups related to representable uninorms, continuous Archimedean t-norms, continuous Archimedean t-conorms and internal uninorms (including the min and the max operator)."

Configurando o tokenizer

In [10]:
tokenizer = RegexTokenizer(inputCol="abstract", outputCol="tokens", pattern="\\W")

df_spark = spark.createDataFrame(df)

#df_sample = df_spark.limit(5)

df_tokenizado = tokenizer.transform(df_spark)

In [11]:
print("Dataframe tokenizado:")
df_tokenizado.select("id", "tokens").show(truncate=False)

Dataframe tokenizado:
+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id                                  |tokens                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|4ab3735c-80f1-472d-b953-fa0557fed28b|[in, this, paper, a, robust, 3d, triangular, mesh, watermarking, algorithm, based, on, 3d, segmentation, is, proposed, in, this, algorithm, three, classes, of, watermarking, are, combined, first, we, segment, the, original, image, to, many, different, regions, then, we, mark, every, type, of, region, with, the, corresponding, algorithm, based, on, their, curvature, value, the, experiments, show, that, our, watermarking, is, robust, against, numerous, attacks, including, rst, transformations, smoothing, additive, random, noise, cropping, simplification, and, remeshing]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|4ab39729-af77-46f7-a662-16984fb9c1db|[we, studied, an, autoassociative, neural, network, with, dynamic, synapses, which, include, a, facilitating, mechanism, we, have, developed, a, general, mean, field, framework, to, study, the, relevance, of, the, different, parameters, defining, the, dynamics, of, the, synapses, and, their, influence, on, the, collective, properties, of, the, network, depending, on, these, parameters, the, network, shows, different, types, of, behaviour, including, a, retrieval, phase, an, oscillatory, regime, and, a, non, retrieval, phase, in, the, oscillatory, phase, the, network, activity, continously, jumps, between, the, stored, patterns, compared, with, other, activity, dependent, mechanisms, such, as, synaptic, depression, synaptic, facilitation, enhances, the, network, ability, to, switch, among, the, stored, patterns, and, therefore, its, adaptation, to, external, stimuli, a, detailed, analysis, of, our, system, reflects, an, efficient, more, rapid, and, with, lesser, errors, network, access, to, the, stored, information, with, stronger, facilitation, we, also, present, a, set, of, monte, carlo, simulations, confirming, our, analytical, results]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de|[it, is, well, known, that, sturmian, sequences, are, the, non, ultimately, periodic, sequences, that, are, balanced, over, a, 2, letter, alphabet, they, are, also, characterized, by, their, complexity, they, have, exactly, n, 1, distinct, factors, of, length, n, a, natural, generalization, of, sturmian, sequences, is, the, set, of, infinite, episturmian, sequences, these, sequences, are, not, necessarily, balanced, over, a, k, letter, alphabet, nor, are, they, necessarily, aperiodic, in, this, paper, we, characterize, balanced, episturmian, sequences, periodic, or, not, and, prove, fraenkel, s, conjecture, for, the, special, case, of, episturmian, sequences, it, appears, that, balanced, episturmian, sequences, are, all, ultimately, periodic, and, they, can, be, classified, in, 3, families]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|4ab3a98c-3620-47ec-b578-884ecf4a6206|[one, of, the, fundamental, challenges, of, recognizing, actions, is, accounting, for, the, variability, that, arises, when, arbitrary, cameras, capture, humans, performing, actions, in, this, paper, we, explicitly, identify, three, important, sources, of, variability, 1, viewpoint, 2, execution, rate, and, 3, anthropometry, of, actors, and, propose, a, model, of, human, actions, that, allows, us, to, investigate, all, three, our, hypothesis, is, that, the, variability, associated, with, the, execution, of, an, action, can, be, closely, approximated, by, a, linear, combination, of, action, bases, in, joint, spatio, temporal, space, we, demonstrate, that, such, a, model, bounds, the, rank, of, a, matrix, of, image, measurements, and, that, this, bound, can, be, used, to, achieve, recognition, of, actions, based, only, on, imaged, data, a, test, employing, principal, angles, between, subspaces, that, is, robust, to, statistical, fluctuations, in, measurement, data, is, presented, to, find, the, membership, of, an, instance, of, an, action, the, algorithm, is, applied, to, recognize, several, actions, and, promising, results, have, been, obtained]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|4ab3b585-82b4-4207-91dd-b6bce7e27c4e|[this, paper, generalizes, previous, optimal, upper, bounds, on, the, minimum, euclidean, distance, for, phase, shift, keying, psk, block, codes, that, are, explicit, in, three, parameters, alphabet, size, block, length, a]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|4ab3e768-78c9-4497-8b8e-9e934cb5f2e4|[queueing, networks, with, multiple, classes, of, customers, play, a, fundamental, role, for, evaluating, the, performance, of, both, software, and, hardware, architectures, the, main, strength, of, product, form, models, in, particular, of, bcmp, queueing, networks, is, that, they, combine, a, flexible, formalism, with, efficient, analysis, techniques, and, solution, algorithms, in, this, paper, we, provide, an, algorithm, that, starting, from, a, high, level, description, of, a, system, and, from, the, definition, of, its, components, in, terms, of, interacting, sub, systems, computes, a, multiple, class, and, multiple, chain, bcmp, queueing, network, we, believe, that, the, strength, of, this, approach, is, twofold, first, the, modeller, deals, with, simplified, models, which, are, defined, in, a, modular, and, hierarchical, way, hence, we, can, carry, on, sensitivity, analysis, that, may, easily, include, structural, changes, and, not, only, on, the, time, parameters, second, maintaining, the, product, form, property, allows, one, to, derive, the, average, system, performance, indices, very, efficiently, the, paper, also, discusses, the]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

In [12]:
#Configurando o stopwords remover
stopwords_remover = StopWordsRemover(inputCol="tokens", outputCol="filtered", stopWords=list(stopwords_en))

In [13]:
df_sem_stopwords = stopwords_remover.transform(df_tokenizado)

In [14]:
df_sem_stopwords.select("id", "filtered").show(truncate=False)

+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|id                                  |filtered                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
+------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|4ab3735c-80f1-472d-b953-fa0557fed28b|[paper, robust, 3d, triangular, mesh, watermarking, algorithm, based, 3d, segmentation, proposed, algorithm, three, classes, watermarking, combined, first, segment, original, image, many, different, regions, mark, every, type, region, corresponding, algorithm, based, curvature, value, experiments, show, watermarking, robust, numerous, attacks, including, rst, transformations, smoothing, additive, random, noise, cropping, simplification, remeshing]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|4ab39729-af77-46f7-a662-16984fb9c1db|[studied, autoassociative, neural, network, dynamic, synapses, include, facilitating, mechanism, developed, general, mean, field, framework, study, relevance, different, parameters, defining, dynamics, synapses, influence, collective, properties, network, depending, parameters, network, shows, different, types, behaviour, including, retrieval, phase, oscillatory, regime, non, retrieval, phase, oscillatory, phase, network, activity, continously, jumps, stored, patterns, compared, activity, dependent, mechanisms, synaptic, depression, synaptic, facilitation, enhances, network, ability, switch, among, stored, patterns, therefore, adaptation, external, stimuli, detailed, analysis, system, reflects, efficient, rapid, lesser, errors, network, access, stored, information, stronger, facilitation, also, present, set, monte, carlo, simulations, confirming, analytical, results]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
|4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de|[well, known, sturmian, sequences, non, ultimately, periodic, sequences, balanced, 2, letter, alphabet, also, characterized, complexity, exactly, n, 1, distinct, factors, length, n, natural, generalization, sturmian, sequences, set, infinite, episturmian, sequences, sequences, necessarily, balanced, k, letter, alphabet, necessarily, aperiodic, paper, characterize, balanced, episturmian, sequences, periodic, prove, fraenkel, conjecture, special, case, episturmian, sequences, appears, balanced, episturmian, sequences, ultimately, periodic, classified, 3, families]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|4ab3a98c-3620-47ec-b578-884ecf4a6206|[one, fundamental, challenges, recognizing, actions, accounting, variability, arises, arbitrary, cameras, capture, humans, performing, actions, paper, explicitly, identify, three, important, sources, variability, 1, viewpoint, 2, execution, rate, 3, anthropometry, actors, propose, model, human, actions, allows, us, investigate, three, hypothesis, variability, associated, execution, action, closely, approximated, linear, combination, action, bases, joint, spatio, temporal, space, demonstrate, model, bounds, rank, matrix, image, measurements, bound, used, achieve, recognition, actions, based, imaged, data, test, employing, principal, angles, subspaces, robust, statistical, fluctuations, measurement, data, presented, find, membership, instance, action, algorithm, applied, recognize, several, actions, promising, results, obtained]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|4ab3b585-82b4-4207-91dd-b6bce7e27c4e|[paper, generalizes, previous, optimal, upper, bounds, minimum, euclidean, distance, phase, shift, keying, psk, block, codes, explicit, three, parameters, alphabet, size, block, length]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|4ab3e768-78c9-4497-8b8e-9e934cb5f2e4|[queueing, networks, multiple, classes, customers, play, fundamental, role, evaluating, performance, software, hardware, architectures, main, strength, product, form, models, particular, bcmp, queueing, networks, combine, flexible, formalism, efficient, analysis, techniques, solution, algorithms, paper, provide, algorithm, starting, high, level, description, system, definition, components, terms, interacting, sub, systems, computes, multiple, class, multiple, chain, bcmp, queueing, network, believe, strength, approach, twofold, first, modeller, deals, simplified, models, defined, modular, hierarchical, way, hence, carry, sensitivity, analysis, may, easily, include, structural, changes, time, parameters, second, maintaining, product, form, property, allows, one, derive, average, system, performance, indices, efficiently, paper, also, discusses]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
|4ab3f7cd-140b-4e29-99d4-f4e8006c4f65|[cmos, oscillator, employing, differential, transistor, pairs, working, class, c, push, pull, configuration, presented, oscillator, exhibits, advantages, enjoyed, complementary, topologies, oscillators, based, single, differential, pair, yielding, substantial, power, consumption, reduction, thanks, class, c, operation, phase, noise, performance, fundamental, conditions, required, keep, transistors, working, class, c, analyzed, detail, shown, optimal, performance, nmos, pmos, transistors, pushed, deep, triode, region, instantaneous, resonator, voltage, simple, circuit, solution, proposed, accommodate, large, oscillation, swing, 0, 18, cmos, prototype, voltage, controlled, oscillator, displays, oscillation, frequency, 6, 09, 7, 50, ghz, phase, noise, 2, mhz, offset, 120, dbc, hz, power, dissipation, 2, 2, mw, state, art, figure, merit, ranging, 189, 191, dbc, hz]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|4ab404e2-6f4b-4fb4-b093-50775e765b13|[statistical, setting, pattern, recognition, problem, number, examples, required, approximate, unknown, labelling, function, linear, vc, dimension, target, learning, class, work, consider, question, whether, bounds, exist, consider, computable, pattern, recognition, methods, assuming, unknown, labelling, function, also, computable, find, case, number, examples, required, computable, method, approximate, labelling, function, linear, grows, faster, vc, dimension, class, computable, function, time, space, constraints, put, predictors, target, functions, resource, consider, training, examples, r, n, r, n, task, pattern, recognition, considered, conjunction, another, learning, problem, data, compression, impossibility, result, task, data, compression, allows, us, estimate, sample, complexity, pattern, recognition]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|4ab4244d-fb3e-49a3-b125-367df3d8e6ba|[first, discuss, general, aspects, micromanipulation, possible, different, approaches, present, new, results, micromanipulation, mechanical, biological, objects, apparatus, use, purposely, developed, workstation, comprising, macro, micro, manipulators, innovative, component, workstation, micro, gripper, fabricated, using, liga, technology, actuated, piezoelectric, actuators, describe, design, fabrication, performance, prototypes, liga, micro, grippers, results, presented, demonstrate, ability, system, manipulate, effectively, micro, mechanical, biological, micro, objects]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|4ab459ce-5f18-4cc0-9627-1dc557eb8b68|[1999, iwan, duursma, defined, zeta, function, linear, code, generating, function, hamming, weight, enumerator, also, defined, homogeneous, polynomials, corresponding, existing, codes, homogeneous, polynomial, invariant, macwilliams, transform, zeta, function, satisfies, functional, equation, formulate, analogue, riemann, hypothesis, far, existing, codes, concerned, riemann, hypothesis, believed, closely, related, extremal, property, article, show, abundant, polynomials, invariant, macwilliams, transform, satisfy, riemann, hypothesis, proof, carried, explicit, construction, polynomials, prove, riemann, hypothesis, certain, class, invariant, polynomials, establish, analogue, enestrom, kakeya, theorem]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |

Como podemos ver, o dataframe ainda contém tokens com apenas uma letra.
Iremos definir uma função para remover esses tokens

In [15]:
print(df_sem_stopwords.columns)

['Unnamed: 0', 'abstract', 'authors', 'n_citation', 'references', 'title', 'venue', 'year', 'id', 'tokens', 'filtered']

In [16]:
from pyspark.sql.functions import udf
from pyspark.sql.types import ArrayType, StringType
import re

In [17]:
def remove_single_letter_tokens(tokens):
    return [token for token in tokens if len(token) > 1]

remove_single_letter_tokens_udf = udf(remove_single_letter_tokens, ArrayType(StringType()))

df_final = df_sem_stopwords.withColumn("filtered", remove_single_letter_tokens_udf(df_sem_stopwords["filtered"]))

df_final.show()

+----------+--------------------+--------------------+----------+--------------------+--------------------+--------------------+----+--------------------+--------------------+--------------------+
|Unnamed: 0|            abstract|             authors|n_citation|          references|               title|               venue|year|                  id|              tokens|            filtered|
+----------+--------------------+--------------------+----------+--------------------+--------------------+--------------------+----+--------------------+--------------------+--------------------+
|         0|In this paper, a ...|['S. Ben Jabra', ...|        50|['09cb2d7d-47d1-4...|A new approach of...|international sym...|2008|4ab3735c-80f1-472...|[in, this, paper,...|[paper, robust, 3...|
|         1|We studied an aut...|['Joaquín J. Torr...|        50|['4017c9d2-9845-4...|Attractor neural ...|      Neurocomputing|2007|4ab39729-af77-46f...|[we, studied, an,...|[studied, autoass...|
|         2|It is well-known ...|['Genevi eve Paqu...|        50|['1c655ee2-067d-4...|A characterizatio...|Electronic Journa...|2007|4ab3a4cf-1d96-4ce...|[it, is, well, kn...|[well, known, stu...|
|         3|One of the fundam...|['Yaser Sheikh', ...|       221|['056116c1-9e7a-4...|Exploring the spa...|international con...|2005|4ab3a98c-3620-47e...|[one, of, the, fu...|[one, fundamental...|
|         4|This paper genera...|['Efraim Laksman'...|         0|['01a765b8-0cb3-4...|Generalized upper...|Ima Journal of Ma...|2015|4ab3b585-82b4-420...|[this, paper, gen...|[paper, generaliz...|
|         5|Queueing networks...|['Simonetta Balsa...|         6|['1c26e228-57d2-4...|Applying BCMP mul...|International Jou...|2015|4ab3e768-78c9-449...|[queueing, networ...|[queueing, networ...|
|         6|A CMOS oscillator...|['Andrea Mazzanti...|        50|['0a09db01-264a-4...|A Push–Pull Class...|IEEE Journal of S...|2013|4ab3f7cd-140b-4e2...|[a, cmos, oscilla...|[cmos, oscillator...|
|         7|In statistical se...|   ['Daniil Ryabko']|         2|['505f493b-e09d-4...|On computability ...|algorithmic learn...|2005|4ab404e2-6f4b-4fb...|[in, statistical,...|[statistical, set...|
|         8|We first discuss ...|['Maria Chiara Ca...|        50|['5ecd70e1-7ccc-4...|Manipulating biol...|international con...|1998|4ab4244d-fb3e-49a...|[we, first, discu...|[first, discuss, ...|
|        10|In 1999, Iwan Duu...|     ['Koji Chinen']|         0|['02d38c7d-3baf-4...|An abundance of i...|Discrete Mathematics|2008|4ab459ce-5f18-4cc...|[in, 1999, iwan, ...|[1999, iwan, duur...|
|        11|Entity Resolution...|['Steven Euijong ...|       211|['0b5e0bfa-12ff-4...|Entity resolution...|international con...|2009|4ab46288-3a29-471...|[entity, resoluti...|[entity, resoluti...|
|        12|Performance analy...|['Todd Mytkowicz'...|        95|['0b279971-aa22-4...|Evaluating the ac...|programming langu...|2010|4ab4c0a1-3c5a-44c...|[performance, ana...|[performance, ana...|
|        13|In motion-compens...|['Tao Fang', 'Lap...|         1|['15430dbb-9ce8-4...|Robust group-of-p...|international sym...|2005|4ab4c17b-a9ac-4f3...|[in, motion, comp...|[motion, compensa...|
|        14|Most of us have t...|['David R. Stoute...|         6|['12a6a20f-d96b-4...|Useful computatio...|ACM Communication...|2007|4ab4e2a8-18c5-47a...|[most, of, us, ha...|[us, taken, exact...|
|        15|This paper addres...|['Awadhesh Srivas...|        50|['517f023f-4d1f-4...|Fast Content Awar...|                 NaN|2008|4ab503e2-d7b4-441...|[this, paper, add...|[paper, addresses...|
|        16|Scalable storage ...|['Ashish Goel', '...|        70|['1d950f41-7ecc-4...|SCADDAR: an effic...|international con...|2002|4ab50bd7-8e59-497...|[scalable, storag...|[scalable, storag...|
|        17|Rare event simula...| ['Werner Sandmann']|        10|['1fbce743-ee10-4...|Importance sampli...|winter simulation...|2005|4ab50fd5-e0e8-44a...|[rare, event, sim...|[rare, event, sim...|
|        18|Freezing toleranc...|['Angelica Lindlö...|         0|['9b8ad98f-1db8-4...|Identification of...|bioinformatics re...|2007|4ab54610-4947-46c...|[freezing, tolera...|[freezing, tolera...|
|        19|This position pap...|['Alan Burns', 'N...|        50|['236bbbbd-56a9-4...|Real-time distrib...|                 NaN|1995|4ab5585e-6a6a-4c9...|[this, position, ...|[position, paper,...|
|        20|a b s t r a c t T...|['Frances E. Pere...|         5|['0983ec0b-f922-4...|On the impact of ...|Computers & Chemi...|2014|4ab572c2-c224-4d2...|[a, b, s, t, r, a...|[constant, pressu...|
+----------+--------------------+--------------------+----------+--------------------+--------------------+--------------------+----+--------------------+--------------------+--------------------+
only showing top 20 rows

In [18]:
df_final = df_final.withColumn("abstract", df_final["filtered"]) \
                   .drop("tokens", "filtered")

In [19]:
df_final.show(truncate=False)

+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+----+------------------------------------+
|Unnamed: 0|abstract                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |authors                                                                                                    |n_citation|references                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |title                                                                                                                           |venue                                                             |year|id                                  |
+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+----+------------------------------------+
|0         |[paper, robust, 3d, triangular, mesh, watermarking, algorithm, based, 3d, segmentation, proposed, algorithm, three, classes, watermarking, combined, first, segment, original, image, many, different, regions, mark, every, type, region, corresponding, algorithm, based, curvature, value, experiments, show, watermarking, robust, numerous, attacks, including, rst, transformations, smoothing, additive, random, noise, cropping, simplification, remeshing]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |['S. Ben Jabra', 'Ezzeddine Zagrouba']                                                                     |50        |['09cb2d7d-47d1-4a85-bfe5-faa8221e644b', '10aa16da-3cc8-4af6-9d66-48037e915d76', '35cb45c3-9408-4096-ab30-bc2e4de3fb5d', '661a342e-a911-4420-b67d-51c75d3b14e9', '779553f3-e4c1-456e-bc01-5eb9d9567541', 'b24ba5c0-fee8-4a3e-9330-17f6564856cd', 'fd1c676d-1296-4f19-89b4-17c7ecd270f3']                                                                                                                                                                                                                                                                                                                                                                                                                                                        |A new approach of 3D watermarking based on image segmentation                                                                   |international symposium on computers and communications           |2008|4ab3735c-80f1-472d-b953-fa0557fed28b|
|1         |[studied, autoassociative, neural, network, dynamic, synapses, include, facilitating, mechanism, developed, general, mean, field, framework, study, relevance, different, parameters, defining, dynamics, synapses, influence, collective, properties, network, depending, parameters, network, shows, different, types, behaviour, including, retrieval, phase, oscillatory, regime, non, retrieval, phase, oscillatory, phase, network, activity, continously, jumps, stored, patterns, compared, activity, dependent, mechanisms, synaptic, depression, synaptic, facilitation, enhances, network, ability, switch, among, stored, patterns, therefore, adaptation, external, stimuli, detailed, analysis, system, reflects, efficient, rapid, lesser, errors, network, access, stored, information, stronger, facilitation, also, present, set, monte, carlo, simulations, confirming, analytical, results]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |['Joaquín J. Torres', 'Jesús M. Cortés', 'Joaquín Marro', 'Hilbert J. Kappen']                             |50        |['4017c9d2-9845-4ad2-ad5b-ba65523727c5', 'b1187381-cc24-471e-b288-5da09c3d4ca9', 'ecf8e7f0-cac6-47e4-9c29-f4241b0e1d7a']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |Attractor neural networks with activity-dependent synapses: The role of synaptic facilitation                                   |Neurocomputing                                                    |2007|4ab39729-af77-46f7-a662-16984fb9c1db|
|2         |[well, known, sturmian, sequences, non, ultimately, periodic, sequences, balanced, letter, alphabet, also, characterized, complexity, exactly, distinct, factors, length, natural, generalization, sturmian, sequences, set, infinite, episturmian, sequences, sequences, necessarily, balanced, letter, alphabet, necessarily, aperiodic, paper, characterize, balanced, episturmian, sequences, periodic, prove, fraenkel, conjecture, special, case, episturmian, sequences, appears, balanced, episturmian, sequences, ultimately, periodic, classified, families]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |['Genevi eve Paquin', 'Laurent Vuillon']                                                                   |50        |['1c655ee2-067d-4bc4-b8cc-bc779e9a7f10', '2e4e57ca-d190-4bc7-b7ad-2e33aca2f574', '508ea83a-035b-4542-a315-9247c172d255', '666a65af-8657-43f6-b765-f2b72a16726a', '8100bfb7-3f6a-4269-bba8-7c4a6a578570', '8e035cc6-d692-4532-bb3c-a6a34b4db83a', 'e10a00d9-bb59-4f19-8f1c-85917bc03b5f']                                                                                                                                                                                                                                                                                                                                                                                                                                                        |A characterization of balanced episturmian sequences                                                                            |Electronic Journal of Combinatorics                               |2007|4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de|
|3         |[one, fundamental, challenges, recognizing, actions, accounting, variability, arises, arbitrary, cameras, capture, humans, performing, actions, paper, explicitly, identify, three, important, sources, variability, viewpoint, execution, rate, anthropometry, actors, propose, model, human, actions, allows, us, investigate, three, hypothesis, variability, associated, execution, action, closely, approximated, linear, combination, action, bases, joint, spatio, temporal, space, demonstrate, model, bounds, rank, matrix, image, measurements, bound, used, achieve, recognition, actions, based, imaged, data, test, employing, principal, angles, subspaces, robust, statistical, fluctuations, measurement, data, presented, find, membership, instance, action, algorithm, applied, recognize, several, actions, promising, results, obtained]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |['Yaser Sheikh', 'Mumtaz Sheikh', 'Mubarak Shah']                                                          |221       |['056116c1-9e7a-4f9b-a918-44eb199e67d6', '05ac52a1-dfa2-4c32-9a54-6c1e58cfcca5', '0b2f71cc-6797-445a-82df-5be29945c0a7', '60cf9842-c3aa-463d-a5cf-17fbb8f99ccd', '7a3bb575-8313-4e77-a008-ee5cde444746', '7eda9b91-21f1-490f-8ef2-f94e81c558a4', '905461e4-643b-4da0-a669-f52318b9e126', 'be336575-9974-411d-b637-45440213cbd4', 'be9527aa-97e2-4951-86d1-cc6130cbb777', 'f0d57def-3340-49be-a1c3-cbc996af8dec']                                                                                                                                                                                                                                                                                                                                |Exploring the space of a human action                                                                                           |international conference on computer vision                       |2005|4ab3a98c-3620-47ec-b578-884ecf4a6206|

In [20]:
df_final_reparticionado = df_final.repartition(20)

In [21]:
spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")

In [ ]:
df_pandas = df_final_reparticionado.toPandas().

In [ ]:
df_final_reparticionado.write.parquet("resources/dblp_v10_clean-stopwords.parquet", mode="overwrite")

Py4JJavaError: An error occurred while calling o138.parquet.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 16 in stage 5.0 failed 1 times, most recent failure: Lost task 16.0 in stage 5.0 (TID 40) (JONAS-PC executor driver): java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.DataOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(Unknown Source)
	at org.apache.spark.api.python.PythonRDD$.write$1(PythonRDD.scala:310)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$writeIteratorToStream$1(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$writeIteratorToStream$1$adapted(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRDD$$$Lambda$2578/939834240.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:751)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:451)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$Lambda$2564/328393937.apply(Unknown Source)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:282)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler$$Lambda$3109/1481041633.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGScheduler$$Lambda$3107/2107484007.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.DataOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(Unknown Source)
	at org.apache.spark.api.python.PythonRDD$.write$1(PythonRDD.scala:310)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$writeIteratorToStream$1(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$writeIteratorToStream$1$adapted(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRDD$$$Lambda$2578/939834240.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:322)
	at org.apache.spark.api.python.PythonRunner$$anon$2.writeIteratorToStream(PythonRunner.scala:751)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.$anonfun$run$1(PythonRunner.scala:451)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread$$Lambda$2564/328393937.apply(Unknown Source)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1928)
	at org.apache.spark.api.python.BasePythonRunner$WriterThread.run(PythonRunner.scala:282)

In [ ]:
import os
variable = os.getenv('HADOOP_HOME')
print(variable)

C:\Dev\hadoop-3.4.1

In [ ]:
#spark.stop()